#version 450
#extension GL_ARB_separate_shader_objects : enable
#extension GL_GOOGLE_include_directive : require


#include "generated/SphericalHarmonicSamples.inc"


// Global coordinates:
//
// X: index of a direction for spherical harmonic
// Y: index of a diffuse sample
//
// Work group:
//
// Z: index of a spherical harmonic coefficient


const uint LOCAL_SIZE = 8;

const uint sphericalHarmonicSamples_precomputedValuesPerSampleCount =
  (sphericalHarmonicSamples_maxBand + 1) * (sphericalHarmonicSamples_maxBand + 1);
const uint sphericalHarmonicSamples_precomputedValuesCount =
  sphericalHarmonicSamples_sampleCount * sphericalHarmonicSamples_precomputedValuesPerSampleCount;

layout(
  local_size_x = LOCAL_SIZE,
  local_size_y = LOCAL_SIZE,
  local_size_z = sphericalHarmonicSamples_precomputedValuesPerSampleCount) in;

layout(binding = 0, set = 0) uniform samplerCube cubemap;

layout(binding = 1, set = 0, std140) readonly buffer samples_t
{
  vec4 directions[sphericalHarmonicSamples_sampleCount];
  vec4 precomputedValues[(sphericalHarmonicSamples_precomputedValuesCount - 1) / 4 + 1];
}
samples;

layout(binding = 2, set = 0, std430) buffer coefficients_t
{
  uvec4 coefficients[sphericalHarmonicSamples_precomputedValuesCount];
};

const mat3 layerToTransform[] = mat3[](
  mat3(vec3(0.0, 0.0, -1.0), vec3(0.0, 1.0, 0.0), vec3(1.0, 0.0, 0.0)),
  mat3(vec3(0.0, 0.0, 1.0), vec3(0.0, 1.0, 0.0), vec3(-1.0, 0.0, 0.0)),
  mat3(vec3(1.0, 0.0, 0.0), vec3(0.0, 0.0, -1.0), vec3(0.0, 1.0, 0.0)),
  mat3(vec3(1.0, 0.0, 0.0), vec3(0.0, 0.0, 1.0), vec3(0.0, -1.0, 0.0)),
  mat3(vec3(1.0, 0.0, 0.0), vec3(0.0, 1.0, 0.0), vec3(0.0, 0.0, 1.0)),
  mat3(vec3(-1.0, 0.0, 0.0), vec3(0.0, 1.0, 0.0), vec3(0.0, 0.0, -1.0)));

shared vec3 currCoefficients[LOCAL_SIZE][LOCAL_SIZE]
                            [sphericalHarmonicSamples_precomputedValuesPerSampleCount];

struct SphericalHarmonicSample
{
  vec3 direction;
  float value;
};

SphericalHarmonicSample getSphericalHarmonicSample(uint index, uint coefficientIndex)
{
  uint precomputedValueIndex =
    index * sphericalHarmonicSamples_precomputedValuesPerSampleCount + coefficientIndex;

  return SphericalHarmonicSample(
    samples.directions[index].xyz,
    samples.precomputedValues[precomputedValueIndex / 4][precomputedValueIndex % 4]);
}

#define SAMPLE_COUNT sphericalHarmonicSamples_sampleCount
#define SAMPLE_DIRECTIONS_ARRAY samples.directions
#include "../impl/EnvironmentDiffuse.inc"

void main()
{
  uint sphericalHarmonicDirIndex = gl_GlobalInvocationID.x;
  uint localSphericalHarmonicDirIndex = gl_LocalInvocationID.x;

  uint diffuseSampleIndex = gl_GlobalInvocationID.y;
  uint localDiffuseSampleIndex = gl_LocalInvocationID.y;

  uint coefficientIndex = gl_LocalInvocationID.z;

  if (sphericalHarmonicDirIndex >= sphericalHarmonicSamples_sampleCount)
  {
    currCoefficients[localDiffuseSampleIndex][localSphericalHarmonicDirIndex][coefficientIndex] =
      vec3(0.0);
    barrier();
    barrier();
    return;
  }

  SphericalHarmonicSample currSample =
    getSphericalHarmonicSample(sphericalHarmonicDirIndex, coefficientIndex);

  uint seed = sphericalHarmonicDirIndex * 1000381 + randomUint(sphericalHarmonicDirIndex) * 71 +
    diffuseSampleIndex * 1237 + randomUint(diffuseSampleIndex);

  vec3 contribution =
    calculateEnvironmentDiffuse(normalize(currSample.direction), 64, seed, cubemap) *
    currSample.value * 4.0 * PI / sphericalHarmonicSamples_sampleCount / gl_NumWorkGroups.y /
    LOCAL_SIZE;

  currCoefficients[localDiffuseSampleIndex][localSphericalHarmonicDirIndex][coefficientIndex] =
    contribution;

  barrier();

  if (localSphericalHarmonicDirIndex == 0)
  {
    vec3 coefficientSum = vec3(0.0);

    for (int j = 0; j < LOCAL_SIZE; ++j)
    {
      coefficientSum += currCoefficients[localDiffuseSampleIndex][j][coefficientIndex];
    }

    currCoefficients[localDiffuseSampleIndex][0][coefficientIndex].xyz = coefficientSum;
  }

  barrier();

  if (localSphericalHarmonicDirIndex == 0 && localDiffuseSampleIndex == 0)
  {
    vec3 coefficientSum = vec3(0.0);

    for (int i = 0; i < LOCAL_SIZE; ++i)
    {
      coefficientSum += currCoefficients[i][0][coefficientIndex];
    }

    for (int channel = 0; channel < 3; ++channel)
    {
      uint valueExpected = 0;

      while (true)
      {
        uint valueSeen = atomicCompSwap(
          coefficients[coefficientIndex][channel],
          valueExpected,
          floatBitsToUint(uintBitsToFloat(valueExpected) + coefficientSum[channel]));

        if (valueSeen == valueExpected)
        {
          break;
        }

        valueExpected = valueSeen;
      }
    }
  }
}
