#version 450
#extension GL_ARB_separate_shader_objects : enable
#extension GL_GOOGLE_include_directive : require


#include "../EnvironmentDiffuse.h"

const int LOCAL_SIZE_X = 16;
const int LOCAL_SIZE_Y = 16;

layout(local_size_x = LOCAL_SIZE_X, local_size_y = LOCAL_SIZE_Y, local_size_z = 1) in;

layout(binding = 0, set = 0) uniform samplerCube cubemap;
layout(binding = 1, set = 0) uniform writeonly image2DArray outCubemap;

const mat3 layerToTransform[] = mat3[](
  mat3(vec3(0.0, 0.0, -1.0), vec3(0.0, 1.0, 0.0), vec3(1.0, 0.0, 0.0)),
  mat3(vec3(0.0, 0.0, 1.0), vec3(0.0, 1.0, 0.0), vec3(-1.0, 0.0, 0.0)),
  mat3(vec3(1.0, 0.0, 0.0), vec3(0.0, 0.0, -1.0), vec3(0.0, 1.0, 0.0)),
  mat3(vec3(1.0, 0.0, 0.0), vec3(0.0, 0.0, 1.0), vec3(0.0, -1.0, 0.0)),
  mat3(vec3(1.0, 0.0, 0.0), vec3(0.0, 1.0, 0.0), vec3(0.0, 0.0, 1.0)),
  mat3(vec3(-1.0, 0.0, 0.0), vec3(0.0, 1.0, 0.0), vec3(0.0, 0.0, -1.0)));

shared vec3 colors[LOCAL_SIZE_Y][LOCAL_SIZE_X];

void main()
{
  uvec2 localCoords = gl_LocalInvocationID.xy;
  uvec3 globalCoords = gl_WorkGroupID.xyz;

  uvec2 imageSize = gl_NumWorkGroups.xy;

  vec3 normal = normalize(
    layerToTransform[globalCoords.z] *
    vec3(
      -1.0 + 2.0 * (globalCoords.x + 0.5) / imageSize.x,
      1.0 - 2.0 * (globalCoords.y + 0.5) / imageSize.y,
      1.0));

  colors[localCoords.y][localCoords.x] = calculateEnvironmentDiffuse(
    normal,
    16,
    globalCoords.x * 1000381 + randomUint(globalCoords.x) * 71 + globalCoords.y * 1237 +
      randomUint(globalCoords.y) + localCoords.x * 1000291 + localCoords.y * 839 +
      randomUint(globalCoords.z) * 13 + 3,
    cubemap);

  barrier();

  if (localCoords.x == 0)
  {
    vec3 colorSum = vec3(0.0);

    for (int j = 0; j < LOCAL_SIZE_X; ++j)
    {
      colorSum += colors[localCoords.y][j];
    }

    colors[localCoords.y][0] = colorSum / LOCAL_SIZE_X;
  }

  barrier();

  if (localCoords.x == 0 && localCoords.y == 0)
  {
    vec3 colorSum = vec3(0.0);

    for (int i = 0; i < LOCAL_SIZE_Y; ++i)
    {
      colorSum += colors[i][0];
    }

    imageStore(outCubemap, ivec3(globalCoords), vec4(colorSum / LOCAL_SIZE_Y, 1.0));
  }
}
