#version 450
#extension GL_ARB_separate_shader_objects : enable
#extension GL_GOOGLE_include_directive : require


#include "generated/SphericalHarmonicSamples.inc"


// Grid:
//
// X: for each harmonic coefficient
//
// Work group:
//
// X: for each sample chunk

const int CHUNK_COUNT = 64;
const float PI = 3.14159265;

layout(local_size_x = CHUNK_COUNT, local_size_y = 1, local_size_z = 1) in;

layout(binding = 0, set = 0) uniform samplerCube cubemap;

const uint sphericalHarmonicSamples_precomputedValuesPerSampleCount =
  (sphericalHarmonicSamples_maxBand + 1) * (sphericalHarmonicSamples_maxBand + 1);
const uint sphericalHarmonicSamples_precomputedValuesCount =
  sphericalHarmonicSamples_sampleCount * sphericalHarmonicSamples_precomputedValuesPerSampleCount;

layout(binding = 1, set = 0, std140) readonly buffer samples_t
{
  vec4 directions[sphericalHarmonicSamples_sampleCount];
  vec4 precomputedValues[(sphericalHarmonicSamples_precomputedValuesCount - 1) / 4 + 1];
}
samples;

layout(binding = 2, set = 0, std430) writeonly buffer coefficients_t
{
  vec4 coefficients[sphericalHarmonicSamples_precomputedValuesCount];
};

struct SphericalHarmonicSample
{
  vec3 direction;
  float value;
};

SphericalHarmonicSample getSphericalHarmonicSample(uint index, uint coefficientIndex)
{
  uint precomputedValueIndex =
    index * sphericalHarmonicSamples_precomputedValuesPerSampleCount + coefficientIndex;

  return SphericalHarmonicSample(
    samples.directions[index].xyz,
    samples.precomputedValues[precomputedValueIndex / 4][precomputedValueIndex % 4]);
}

shared vec3 currCoefficients[CHUNK_COUNT];

void main()
{
  uint chunkIndex = gl_LocalInvocationID.x;
  uint coefficientIndex = gl_WorkGroupID.x;

  uint chunkSize = sphericalHarmonicSamples_sampleCount / CHUNK_COUNT;
  uint bigChunkCount = sphericalHarmonicSamples_sampleCount % CHUNK_COUNT;

  uint chunkBegin;
  uint chunkEnd;
  if (chunkIndex < bigChunkCount)
  {
    chunkBegin = chunkIndex * (chunkSize + 1);
    chunkEnd = (chunkIndex + 1) * (chunkSize + 1);
  }
  else
  {
    chunkBegin = bigChunkCount + chunkIndex * chunkSize;
    chunkEnd = bigChunkCount + (chunkIndex + 1) * chunkSize;
  }

  vec3 currCoefficient = vec3(0.0);

  for (uint i = chunkBegin; i < chunkEnd; ++i)
  {
    SphericalHarmonicSample currSample = getSphericalHarmonicSample(i, coefficientIndex);

    vec3 color = texture(cubemap, currSample.direction).rgb;

    currCoefficient += color * currSample.value;
  }

  currCoefficients[chunkIndex] = currCoefficient;

  barrier();

  if (chunkIndex == 0)
  {
    vec3 coefficient = vec3(0.0);

    for (uint i = 0; i < CHUNK_COUNT; ++i)
    {
      coefficient += currCoefficients[i];
    }

    coefficients[coefficientIndex] =
      vec4(coefficient * 2.0 * PI / sphericalHarmonicSamples_sampleCount, 1.0);
  }
}
